### ISSUE TITLE
 Add K2 stuff

### ISSUE THREAD

**Issue by GeneralTanker** [harag-on-steam/se-recycling-extras#1]
Thanks for the IBC support there is another mod that could use some se recycling support. Krastorio 2 + Space Exploration is a popular mod combo that has some items that use recycle recipes. The ones I can think of are the Sentinel (a small radar with no scanning ability), Advance radar and Substation Mk2.

**Comment by harag-on-steam** [comment]
Why these in particular? Because they become obsolete with radar pylons? Those are rather late-tech.

So far I've added items to the mod where there's a reuse for the main ingredient (chests, pipes) or there's a large return of basic materials from the sheer quantity of recycled items (IBC).

I don't forsee either when recycling the substation/radar Mk2 into Mk1.
And the sentinel is so dirt cheap that I just wouldn't bother to recycle it.

It took me a while to find the substation Mk2 by the way - had to find the startup setting for it. That's also a good way to get rid of it ;-)

**Comment by harag-on-steam** [comment]
Added in 2a37461a37d022402b393e6a0f0a3feaa0e2c60b
